module.exports = {
  sayHello: 'Hey there! How may I help you?',
  notRegistered: 'You must register yourself with the bot first, try: \'/start\'',
  welcomeBack: 'Welcome back!',
  askName: 'What\'s the name of the person?',
  askNameTransaction: 'Who did you make the transaction with?',
  askAmount: 'What was the amount spent? (Enter a -ve value if you spent money)',
  askDescription: 'What was the transaction for?',
  userAdded: 'User added successfully.',
  nameExists: 'This name already exists, try a different one.',
  askTransactionDetails: 'Enter the amount, friend\'s name, date, description (separated by commas, enter a +ve amount if you paid, otherwise enter a -ve amount).',
  askNameCalculate: 'Who do you want to check your payables with?',
  transactionAdded: 'Your transaction has been added',
  understandFailure: 'I don\'t understand, try using a command.',
  actionAborted: 'Your action has been aborted',
  serverError: 'Server Error!',
  failureMessage: 'Your task could not be completed, try again.',
  commandList: [
    ['View Users', 'View Transactions'],
    ['Add User', 'Add Transaction'],
  ],
};
